Escape special XML characters
vmichalak/sonos-controller pull request #7
Opened 2017-10-23 18:58 UTC by mguntli

While I was trying to start a playlist from Google Play Music, I noticed that it didn't work because the special characters were not escaped.
<, >, &, " and ' all have special meanings in XML and have to be represented by entities.

Example from Google Play Music:
`sonosDevice.playUri("x-sonosapi-radio:vy_wPybY9vRCoaCMySC_D6Ol9WJ1aoH97kTmNIzBZ667Frppf2koUq7ZH7OJ9bXx41s_K0RZBSA?sid=151&flags=8300&sn=3", null);`

2017-10-23 19:17 UTC, vmichalak requested changes
I think it's better to use URLEncoder.encode() java method than your home made method.

2017-10-23 19:17 UTC, vmichalak commented on src/main/java/com/vmichalak/sonoscontroller/CommandBuilder.java
> +    private String escapeSpecialCharacters(String value) {
Why you doesn't use `URLEncoder.encode()` ?

2017-10-23 19:38 UTC, mguntli commented
Sorry was too early with pushing: UrlEncoder does the wrong escaping!
--> maybe I should have written a UnitTest for it ;-)

2017-10-23 19:45 UTC, vmichalak commented
Write a unit test that reproduces your problem please. It will be better for maintenance in future.

2017-10-23 19:52 UTC, mguntli commented
How do you paste your URI? Because if they are already escaped, it will break the system as well..
I retrieve the playlists URI from my Sonos Favorites with https://github.com/jishi/Jishi.Intel.SonosUPnP

2017-10-23 19:58 UTC, vmichalak commented
For the moment with playURI method i only use mp3 or radio feed, and it works well ;)

2017-10-28 12:34 UTC, mguntli commented
Hi Valentin

Current approach: detect if the string is already escaped, if not escape the XML characters.
https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringEscapeUtils.html#escapeXml(java.lang.String)

I will write a corresponding unit test for it :-)
Input:
- unescaped URI: "x-sonosapi-radio:vy_wPy0RZBSA?sid=151&flags=8300&sn=3"
- escaped URI: "x-sonosapi-radio:vy_wPy0RZBSA?sid=151&amp;flags=8300&amp;sn=3"

Expected result: "x-sonosapi-radio:vy_wPy0RZBSA?sid=151&amp;flags=8300&amp;sn=3"

2017-11-01 10:31 UTC, vmichalak commented
I think i gonna add org.apache.commons.commons-text dependency for this problem. It's more simple.

2017-11-01 12:38 UTC, mguntli commented
I agree, my solution is kind of "self-made" since I didn't want to include any external dependency into your library.
Please keep in mind that you don't double escape already escaped characters (e.g. "&amp;" should not result in "&amp;amp;"

2017-11-01 13:17 UTC, vmichalak commented
It's done on master ! Thanks for your help 👍

2017-11-02 10:28 UTC, closed without merging